- cmd/falco_install.go
- cmd/install.go
- cmd/probe_install.go
- cmd/root.go
- go.mod
- go.sum
- main.go
- pkg/probeloader/loader.go
/kind feature
/area library
/area cli
This PR ports the `httploader` tool from this PR on Falco https://github.com/falcosecurity/falco/pull/776 to the falcoctl under the form of `falcoctl install probe`. This tool will figure out how to download the pre-built Falco probe for this kernel (the kernel module) and load it.
Fixes #20 
```release-note
cli: new command falcoctl install probe
```
> falcoctl install probe

- cmd/psp_conv.go
- pkg/converter/psp/converter.go
- pkg/converter/psp/k8s_psp_rules_template.go
Add the ability to add a prefix to all generated lists, macros, and
rules. This makes it easier to load multiple rules files generated from
different PSPs without the generated rules/macros/lists overlapping with
each other.
The actual prefix to add is provided as a parameter to
NewConverter(). It can be a blank string, in which case the PSP name is
used as the prefix. If the name is missing for some reason, use the
string "psp".
> /kind bug
/kind cleanup
> /kind design
/area library
> /area cli
> /area tests
**What this PR …
> Add a prefix to all generated lists/rules

- pkg/converter/psp/converter.go
- pkg/converter/psp/k8s_psp_rules_template.go
In some cases, someone might want to generate a set of rules without any
restrictions on image. (For example, everything in a cluster, or in a
namespace, etc).
To help support this, make the annotation falco-rules-psp-images
optional. If not present, the generated rules will match all images.
> /kind bug
/kind cleanup
> /kind design
/area library
> /area cli
> /area tests
Fixes #
**Does this PR introduce a …
> Make the annotations for psp->rules optional

- cmd/psp_conv.go
- pkg/converter/psp/converter.go
- pkg/converter/psp/k8s_psp_rules_template.go
/kind bug
> /kind design
/area library
> /area cli
> /area tests
Fixes #
Tests for this are in https://github.com/falcosecurity/falco/pull/899.
```release-note
Don't allow spaces/dashes in the name prefix when converting psps to falco rules.
```
> No dashes name prefix

- cmd/probe_install.go
- cmd/probe_install_linux.go
Co-Authored-By: Leonardo Di Donato <leodidonato@gmail.com>
Signed-off-by: Lorenzo Fontana <lo@linux.com>
/kind bug
/area cli
Allow falcoctl to be built on systems that don't have a linux kernel.
This works by disabling commands that require a linux kernel when building for OSes that don't have one.
The only command we had to disable is `falcoctl install probe` which installs the kernel driver in the current kernel.
This is how the command looks on a windows machine with this PR.
Fixes #
```release-note
Falcoctl support for Windows
```
> build: allow falcoctl to be built on non-linux machines by disabling the probe loader on GOOS != linux

- .gitignore
- .goreleaser.yml
- release.md
Signed-off-by: Lorenzo Fontana <lo@linux.com>
/kind feature
NONE
We want to have all the releases done in the same way.
Using goreleaser we can produce the same artifacts regardless who is the maintainer doing the release by minimizing the manual steps. This also adds documentation for the single manual step we have to do
In the future this manual step can be automated by a CI when this project will have one.
Fixes #24 
```release-note
NONE
```
> build: releases using goreleaser

- pkg/converter/psp/converter.go
The current PSP converter allows parsing PSPS that contain extra fields,
for example:
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
creationTimestamp: null
name: test_psp
annotations:
falco-rules-psp-images: "[nginx]"
not-a-real-field: nope
spec:
privileged: false
fsGroup:
rule: RunAsAny
runAsUser:
rule: RunAsAny
seLinux:
rule: RunAsAny
supplementalGroups:
rule: RunAsAny
volumes:
- secret
```
Change this by using a json decoder with the DisallowUnknownFields() option.
Signed-off-by: Mark Stemm <mark.stemm@gmail.com>
> /kind bug
> /kind design
> …
> Parse PSPs strictly, disallowing unknown fields

- cmd/probe_install_linux.go
/kind bug
/kind cleanup
/area cli
Forces the user to specify a Falco version for which to download the probe via the `install probe` command.
NONE
NONE
```release-note
fix: specifying Falco version when installing probe is mandatory now
```
> fix(cmd): falco version is mandatory (and has no default) 

- cmd/psp_conv.go
- pkg/converter/psp/converter.go
- pkg/converter/psp/k8s_psp_rules_template.go
Add the ability to limit generated rules to specific namespaces (for k8s
audit events). If an annotation falco-rules-psp-namespaces is present on
the PSP, those namespaces are populated into a list _psp_namespaces and
used by a macro _psp_match_namespace.
You can also provide a slice of namespaces to the converter
GenerateRules method. This will be used if the psp has no annotation.
Signed-off-by: Mark Stemm <mark.stemm@gmail.com>
> /kind bug
> /kind design
/kind feature
> /area cli
> /area tests
**What this …
> Add ability to limit generated rules to namespaces

- pkg/kubernetes/falco.go
/kind bug
/area cli
This PR adds cleanup functionality to cleanup non-namespaced falco objects (clusterrole, clusterrolebinding and auditsink). This is needed as these components are currently left behind after a delete.
Fixes #48 
Not sure this is the _best_ way to do this as it has the object names hard-coded. However it does clean up the left behind objects which is missing at this point.
```release-note
NONE
```
> Add cleanup for cr, crb and auditsink

- cmd/install_tls_linux.go
- pkg/tls/generator.go
/kind bug
/kind feature
/area cli
This PR attempts to:
- fix the path in which the certs have to be written (at the moment it writes them in `/etc/falco` but the default path is `/etc/falco/certs`)
- fallbacks to environment variables for `install tls` flags (and uses defaults only in case there are not respective environment variables)
Fixes #52 
```release-note
update(cmd): env variable fallbacks for install tls flags
fix(pkg/tls): put certs into /etc/falco/certs
fix(pkg/tls): correct server cert signing
```
> `install tls`: defaults, correct paths, gen client certs, fix server certs

- cmd/install_tls.go
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
/kind cleanup
Fixes a typo in the `install tls` command.
NONE
```release-note
NONE
```
> fix(cmd): typo in install tls command

- go.mod
- pkg/kubernetes/audit.go
- pkg/kubernetes/falco.go
Create AuditSink idempotently to fix #47 
/kind bug
/area library
/area cli
It creates the AuditSink if it doesn't exist, and updates when it does. It also refactors to use the apierrors package for error checking.
Fixes #47
Added small refactor to use apierrors package to reduce hardcoding for error checking
Added a log line that to the output that is user-facing
```release-note
fix: Creation of AuditSink isn't idempotent (#47)
```
> Make AuditSink creation idempotent

- cmd/install_module_linux.go
/kind bug
> /kind design
/area cli
> /area tests
Currently, `go build .` returns the following errors:
```
cmd/install_module_linux.go:88:28: undefined: kernelmoduleloader.GetKernelConfigHash
cmd/install_module_linux.go:93:31: undefined: kernelmoduleloader.GetKernelRelease
```
because of wrong function names. This PR just fixes this issue.
#76 
**Does this PR introduce a user-facing …
> fix(cmd): correct undefined func calls

- go.mod
- go.sum
- pkg/tls/generator.go
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
/kind bug
/kind cleanup
> /kind design
/area library
> /area cli
> /area tests
This PR simplifies and cleanups the TLS generator by removing the `github.com/spacemonkeygo/openssl` dependency. 
Furthermore, assuming we just need minimal implementation, this PR also improves several aspects:
- Remove unnecessary CSRs and Subjects fields
- Improve naming and comments
We needed this mainly because `github.com/spacemonkeygo/openssl` has …
> refactor(pkg/tls): simplified TLS implementation

- .github/workflows/integration.yaml
> /kind bug
> /kind design
> /area cli
> /area tests
For each PR the CI builds the falcoctl binaries for multiple OS and architectures. The current workflow uses `goreleaser` and it takes up to 15 minutes to finish the build. The job runs on a single github runner and `goreleaser` by default uses all the available CPUs to parallelize the build process but unfortunately, the runners have only two cores. 
The new …
> update(CI/build): build falcoctl binaries without using goreleaser

- cmd/internal/utils/validate.go
- cmd/registry_login.go
- cmd/registry_pull.go
- cmd/registry_push.go
- pkg/output/output.go
> /kind bug
> /kind design
/area cli
> /area tests
This PR adds a common check for `login, push and pull` commands. It makes sure that the remote registry is reachable and that we have the required permissions to push and pull artifacts. In case of errors it prints an understandable error on why the command failed instead of printing the full stack error. The users can still have the full error by enabling the …
> update(cmd): check if registry is reachable before interacting with it

- pkg/index/index.go
- pkg/index/index_test.go
/kind feature
/area library
```go
// Normalize the index to the canonical form (i.e., entries sorted by name,
// lexically byte-wise in ascending order).
//
// Since only one possible representation of a normalized index exists,
// a digest of a normalized index is suitable for integrity checking
// or similar purposes.
// Return an error if the index is not in a consistent state.
```
As a bonus point, having a canonical form reduces the likelihood of git conflicts when an automated tool updates the index.
Fixes #
> new(pkg/index): index normalization func

- cmd/index_add.go
- cmd/index_update.go
- pkg/index/fetch.go
/kind bug
> /kind design
/area library
> /area cli
> /area tests
Correctly fill the entryByName map also when fetching an index remotely so that index normalization doesn't fail
Fixes #
> fix: create an index with consistent state also when fetching it

- cmd/internal/utils/validate.go
/kind bug
> /kind design
/area cli
> /area tests
Before interacting with the remote registry we check that:
* the registry implements the right API i.e. Docker Registry API V2;
* and that we are authenticated;
But some commands such as the `falcoctl registry pull` should not check we are authenticated if no credentials are provided. When interacting with public repositories we do not need to be authenticated. …
> fix(cmd/utils): support connection checking for remote registries without authentication

- cmd/artifact_search.go
- pkg/index/index.go
> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
Improve artifact search command by using Levenshtein Distance and partial matching on keywords.
This allows returning meaningful results also if a name is e.g. mistyped or we have only a partial match on keywords (for instance `aws_cloudtrail` keyword can now match with `aws`). To implement the Levenshtein distance a DP matrix is used. 
Future PR will also add a way to look up using regular expressions. …
> update: improve artifact search command

- cmd/root.go
- cmd/testdata/help.txt
- cmd/testdata/noargsnoflags.txt
- cmd/testdata/wrongflag.txt
- cmd/tls.go
- cmd/tls_install.go
This allow to be compliant with the naming we have chosen for this repo and the other commands.
> /kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
The naming convention for command is object and then verb, i.e `artifact install`.
To respect this, change `install tls` with `tls install`.
Fixes #
> chore: rename `install tls` command to `tls install` to be compliant with new naming convention

- cmd/artifact_install.go
- cmd/internal/utils/validate.go
- cmd/root.go
- cmd/testdata/help.txt
- cmd/testdata/noargsnoflags.txt
- cmd/testdata/wrongflag.txt
- go.mod
- go.sum
- pkg/options/common_options.go
- pkg/output/output.go
- pkg/output/output_test.go
- pkg/output/tracker.go
> /kind bug
> /kind design
/kind feature
/area cli
> /area tests
This PR adds a ne global flag `--disable-styling` flag makes `falcoctl` tool output plain text by disabling spinners, progress bars, and colors. `falcoctl` can determine if it is not attached to a TTY and disable the styling. Furthermore, the user can forcibly disable the styling by using the --disable-styling flag.
Default output of `falcoctl`:
```bash
❯ …
```
> feature(cmd): add new global flag --disable-styling

- .github/workflows/integration.yaml
- .goreleaser.yml
It strips off information not needed during execution and reduces the size of the resulting binary.
> /kind bug
> /kind design
> /area cli
> /area tests
This PR adds two new flags when building `falcoctl` that reduces the size of the binary.
Fixes #
> update(ci): use -ldflags="-s -w" when building falcoctl

- cmd/artifact_install.go
- cmd/internal/utils/registry.go
- cmd/registry_pull.go
- cmd/registry_push.go
- pkg/oci/puller/puller.go
- pkg/oci/pusher/pusher.go
- pkg/oci/pusher/pusher_test.go
- pkg/output/tracker.go
> /kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
This PR adds some util functions to create the pusher, puller, and client for a given registry. By doing so we remove duplicated code across the commands that need to create a pusher or puller.
Furthermore, all the progress tracker used by the pusher and puller now lives under the `output` package.
This refactor is needed for the …
> refactor(cmd): remove duplicated code when creating pullers and pushers

- Makefile
Signed-off-by: Luca Guerra <luca@guerra.sh>
/kind bug
/area tests
If you run the Makefile on a new system it will download a new version of GCI and `make fmt` won't work (you see a help message repeated for each file). That is because apparently the CLI standard changed. Update it to the latest version.
Fixes #
> fix(build): use new-style GCI CLI

- internal/artifact/install/install.go
- internal/config/config.go
…s to internal/config package
> /kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
Move default installation paths for `plugins` and `rulesfiles` to `internal/config` package
Fixes #
> chore(artifact/install): move default paths for plugins and rulesfiles to internal/config package

- internal/artifact/install/install.go
- internal/utils/extract.go
> /kind bug
> /kind design
/area library
> /area cli
> /area tests
Return full path of the extracted files in ExtractTarGz func. Having the path of the extracted files simplifies subsequent operations like moving around the files if we extract them in a temporary dir.
Fixes #
> update(internal/utils): return full path of the extracted files in ExtractTarGz func

- pkg/output/tracker.go
> /kind bug
> /kind design
/area library
> /area cli
> /area tests
This allows initialization of a `puller/pusher` without a tracker by passing a nil printer using the `NewTracker` function without explicitly setting the Tracker to nil.
Furthermore, uniforms the output messages by using the printer interface.
Fixes #
> update(output/tracker): return a nil tracker if the printer is nil

- cmd/artifact.go
- cmd/root.go
- internal/artifact/follow/doc.go
- internal/artifact/follow/follow.go
- internal/config/config.go
- internal/follower/doc.go
- internal/follower/follower.go
- internal/utils/validate.go
- pkg/oci/puller/puller.go
- pkg/options/common_options.go
> /kind bug
> /kind design
/kind feature
/area cli
> /area tests
This PR adds the `artifact follow` command:
```bash
❯ ./falcoctl artifact follow --help
Follow a list of artifacts from remote registry. It periodically
checks if the artfacts changed and downloads the latest version based on the configured
tags.
Artifacts are passed as arguments. By just providing the name of the artifact the
command will search for the artifact in the configured index files (see index …
```
> feat(artifact/follow): add new command "artifact follow"

- pkg/oci/pusher/pusher.go
> /kind bug
/kind cleanup
> /kind design
/area library
> /area cli
> /area tests
Use default concurrency for tagging equal to 1. For sure this is not a bottleneck and it allows showing tags in proper order in the below section for our CI. 
Fixes #
> chore: use default tag concurrency equal to 1

- internal/utils/registry.go
- pkg/oci/authn/client.go
- pkg/oci/platforms.go
- pkg/oci/puller/puller.go
- pkg/oci/pusher/pusher.go
- pkg/oci/registry/registry.go
- pkg/oci/repository/repository.go
Co-authored-by: Lorenzo Susini <susinilorenzo1@gmail.com>
> /kind bug
/kind cleanup
> /kind design
/area library
/area cli
> /area tests
Simplify the creation of the `oci client` by returning the `remote.Client` interface instead of a custom `struct` that holds the same interface.
Fixes #
> refactor(oci/client): avoid yet another wrapper for the oci client

- pkg/oci/repository/repository.go
Examples: v0.1, v2 should be correctly parsed.
/kind bug
> /kind design
/area library
> /area cli
> /area tests
Be more tolerant when parsing tags that to not strictly adhere  to semver specification such as `v0.2 or v2`.
Fixes #
> fix(pkg/oci/repository): do not error when parsing semver tags that do not strictly adhere to semver

- pkg/oci/pusher/options.go
> /kind bug
> /kind design
/area library
> /area cli
> /area tests
Remove hugeParam warning when running the linter.
Fixes #
> fix(linting): remove hugeParam warning

- .github/workflows/codeql-analysis.yaml
> /kind bug
> /kind design
> /area cli
> /area tests
Fix `codeql` workflow by setting the branch name to `main`
Fixes #
> fix(ci): use main branch instead of master in codeql workflow

- internal/follower/follower.go
- internal/utils/move.go
/kind bug
> /kind design
/area library
> /area cli
> /area tests
The `rename` system call can fail if source and destination are in different types of filesystems. In that case, just add the logic to do a manual copy of the file.
Fixes #
> fix: use a move function that copies content of a file if rename fails

- internal/artifact/follow/follow.go
> /kind bug
> /kind design
/kind feature
/area library
> /area cli
> /area tests
Since `falcoctl` can be run as sidecar container or in a systems unit, ensure that Falco has time to start up and expose the versions endpoint. This PR add a simple retry logic with exponential backoff using a custom http.RoundTripper.
It is possible to debug what is happening using the verbose flag.
Fixes # …
> update: add retry logic when retrieving falco versions

- pkg/oci/pusher/pusher.go
Signed-off-by: Luca Guerra <luca@guerra.sh>
/kind bug
/area library
When calling the `Push()` function, if tags are specified via `WithTags()` with a repo name without an explicit reference in the name, only the provided tags should be pushed and not `latest`. In all other cases, the behavior should not change.
Fixes #
> fix(pusher): automatically add latest only if no other tag was specified

- cmd/registry/auth/oauth/oauth.go
/kind bug
> /kind design
/area cli
> /area tests
The help message for "falcoctl registry auth oauth" command was missing the hostname parameter.
Fixes #
> fix(cmd): arg missing in usage message of registry auth oauth

- .github/workflows/docker-image.yaml
- .github/workflows/integration.yaml
- .github/workflows/release.yaml
- .goreleaser.yml
- Makefile
- build/Dockerfile
/kind bug
> /kind design
> /area cli
> /area tests
Falcoctl version is set at build time. This PR adjusts the CI to always set the correct version when publishing a `falcoctl` artifact being it a binary or an OCI image.
#236 
Fixes #
> fix(version): correctly set falcoctl version at build time

- internal/config/config.go
/kind bug
> /kind design
/area cli
> /area tests
Using `--config` parameter, the tool searched only for the default config filename ("falcoctl").
Fixes #
NONE
> fix(internal): wrong config file name used

- cmd/artifact/artifact.go
- cmd/artifact/follow/follow.go
- cmd/artifact/install/install.go
- cmd/index/add/add.go
- cmd/index/remove/remove.go
- cmd/index/update/update.go
- internal/config/config.go
- internal/utils/validate.go
- pkg/index/cache/cache.go
- pkg/index/cache/doc.go
- pkg/index/config.go
- pkg/index/constants.go
- pkg/index/index.go
- pkg/index/index_test.go
- pkg/options/common_options.go
> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
Since index files can be overwritten using ENV variables we needed a new solution to handle them on a per-command basis. Added an in-memory caching system that controls the index files during the command execution.
Furthermore, it handles loading and saving the index cache from/to the filesystem.
The files that track the indexes are saved to ~/.config/falcoctl.
Fixes # …
> new(index-caching): add in-memory cache mechanism for index files

- cmd/artifact/follow/follow.go
- cmd/artifact/install/install.go
- internal/follower/follower.go
- internal/utils/fs.go
/kind bug
> /kind design
> /area cli
> /area tests
If the destination directory for the artifacts (`--rulesfiles-dir` or `--plugins-dir`) doesn't exist, the command fails.
Fixes #
NONE
> fix: create artifact destination dir if not present

- cmd/artifact/info/info.go
- cmd/artifact/list/artifact_list.go
- cmd/artifact/search/artifact_search.go
/kind bug
> /kind design
/area cli
> /area tests
Also `artifact search` and `artifact list` commands need to use the configured indexes to provide their output.
Fixes #
> fix: use index cache in artifact commands

- cmd/artifact/follow/follow.go
- cmd/artifact/install/install.go
- internal/config/config.go
- internal/follower/follower.go
- pkg/oci/puller/puller.go
- pkg/oci/types.go
> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
Falcoctl is able to download any kind of artifacts, including shared libraries that could be potentially used by Falco and loaded. For security reasons, we want to let users be able to decide which kind of artifacts falcoctl is allowed to pull by means of a whitelist. If the list is empty everything is allowed for ease of use. 
**Which issue(s) this PR …
> new: introduce allowedTypes

- cmd/artifact/info/info.go
- pkg/oci/repository/repository.go
/kind bug
> /kind design
/area cli
> /area tests
This PR changes the output of the `artifact info` command. Available `tags` are now printed as retrieved from the remote repository.
Old output:
```bash
REF                                     TAGS                              
ghcr.io/falcosecurity/rules/falco-rules 0.0.0 0.1.0-rc1 0.1.0 0.1.0 latest
```
New output:
```bash
REF …
```
> fix(artifact/info): print tags in their original format

- cmd/artifact/follow/follow.go
- cmd/artifact/install/constants.go
- cmd/artifact/install/install.go
This PR adds a tiny refactoring and cleanup on `artifact install` and `artifact follow` commands.
In details, adds sharing of flag names as constants between packages and cleans up unneeded commands' description.
/kind cleanup
/area cli
To remove duplicated code and improve maintainability.
To cleanup commands' documentation.
NA
NA
> refactor(cmd/artifact): share flags and cleanup descriptions

- cmd/registry/auth/basic/basic.go
- cmd/registry/auth/oauth/oauth.go
- cmd/registry/pull/pull.go
- cmd/registry/push/push.go
- cmd/registry/registry.go
- internal/login/doc.go
- internal/login/login.go
/kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
`falcoctl registry pull/push` commands do not parse `ENV` variables and `config file` for credential values. In order to `pull/push` artifacts to private registries we need to explicitly run `falcoctl registry auth` command. This PR allows for credentials to be passed directly to `pull/push` commands using `ENV` variable and/or `config file`.
Fixes #
**Special notes for your …
> fix(cmd/registry): login to registry before running pull/push cmds

- Makefile
Latest golangci-lint fixes some issues with go 1.20
> /kind bug
> /kind design
> /area cli
> /area tests
Bump golangci-lint version to `1.52.2`.
The latest version fixes some issues when linting `go 1.20`.
Fixes #
> update(Makefile): bump golangci-lint version to 1.52.2

- cmd/index/remove/remove.go
Furthermore debug messages are printed when --verbose flag is set.
> /kind bug
> /kind design
/kind feature
/area cli
> /area tests
Add output messages for `falcoctl index remove` command. The following snippet shows the outputs when running the command with `--verbose flag set to true:
```bash
❯ falcoctl index remove falcosecurity falcosecurity1 -v
INFO  Creating in-memory cache using indexes file "/home/aldo/.config/falcoctl/indexes.yaml" and indexes directory …
```
> feat(index/remove): add output messages for index remove command

- cmd/artifact/artifact.go
- cmd/artifact/list/artifact_list.go
- cmd/artifact/search/artifact_search.go
/kind bug
> /kind design
/area cli
> /area tests
The artifact command registers a preRun function that authenticates the configured registries in the configuration file. But not all the subcommands need authentication. This PR prevent the authentication logic to run for subcommands that do not require it.
Furthermore, it prevents `artifact search` from printing the usage in case of errors.
Fixes #281 
**Special notes for …
> fix(cmd/artifact): authenticate only for subcommands that require it

- .github/workflows/docker-image.yaml
- .github/workflows/release.yaml
/kind feature
/area tests
This updates the CI/CD process so that:
1. only container images for releases are signed (and not main)
2. uses the env variable `COSIGN_YES` for cosign 2.0
cc @developer-guy 
Fixes #
> update(ci): only sign releases

- cmd/registry/auth/basic/basic.go
- pkg/oci/constants.go
/kind cleanup
/area cli
The `auth basic` command assumes `ghcr.io` as default oci registry when no hostname is specified. Given that `falcoctl` is a generic tool there is no good reason to keep this default value. 
Fixes #
> fix(cmd/registry/auth/basic): removed default oci registry

- pkg/oci/pusher/pusher.go
/kind bug
> /kind design
/area cli
> /area tests
It seems that ECR does not support annotations on the descriptor of the OCI image configuration. This fix consists in clearing the annotations map of the config descriptor when created. By default the filestore.Add method adds the "org.opencontainers.image.title" annotation.
Fixes #
#302 
> fix(cmd/push): correctly push artifacts to ECR registry

- cmd/artifact/artifact.go
- cmd/artifact/follow/follow.go
- cmd/artifact/info/info.go
- cmd/artifact/install/install.go
- cmd/artifact/list/artifact_list.go
- cmd/artifact/search/artifact_search.go
- cmd/cli_test.go
- cmd/cmd_suite_test.go
- cmd/index/add/add.go
- cmd/index/index.go
- cmd/index/list/list.go
- cmd/index/remove/remove.go
- cmd/index/update/update.go
- cmd/registry/auth/auth.go
- cmd/registry/auth/basic/basic.go
- cmd/registry/auth/gcp/gcp.go
- cmd/registry/auth/oauth/oauth.go
- cmd/registry/pull/pull.go
- cmd/registry/push/push.go
- cmd/registry/registry.go
- cmd/root.go
- cmd/version/version.go
- cmd/version/version_test.go
- pkg/options/artifact.go
- pkg/options/common.go
- pkg/options/registry.go
> /kind bug
/kind cleanup
> /kind design
/area library
/area cli
> /area tests
Follow Golang naming best practices for CLI options.
Fixes #
> refactor: rename options dropping suffix

- build/Dockerfile
> fix(build): use golang 1.21 and up to date alpine image in dockerfile.

- cmd/root.go
- main.go
/kind bug
> /kind design
/area cli
> /area tests
The context used to handle the signals is not propagated to the sub-commands. This makes `falcoctl` unresponsive to signals sent to it. This commit fixes this behavior by correctly passing the context that handles the signals.
Fixes #
> fix(cmd): correctly propagate signal handler to sub-commands

- .github/workflows/lint.yaml
- cmd/artifact/info/info.go
/kind bug
> /kind design
/area cli
> /area tests
The command should exit when the context is canceled by a termination signal. In such a case, the command prints the reason why it exited. 
Furthermore, the table header is printed to stdout only when data is found for the artifacts.
Fixes #
> fix(cmd/info): handle "context canceled" errors

- .golangci.yml
- cmd/root.go
- cmd/tls/install/install.go
- cmd/tls/tls.go
- pkg/install/tls/generator.go
- pkg/install/tls/handler.go
/kind cleanup
/kind feature
/area cli
- add some log messages to inform user when generating the tls certificates
when using this command I felt lost in what was going on and did not see any outputs when the command succeed.
This PR add some logs just to inform the user what is going on
```
$ ./falcoctl tls install
INFO: Generating certificates in /Users/cpanato/code/src/github.com/falcosecurity/falcoctl directory
INFO: Saving server.key to /Users/cpanato/code/src/github.com/falcosecurity/falcoctl
INFO: Saving client.key to /Users/cpanato/code/src/github.com/falcosecurity/falcoctl
INFO: Saving ca.key to /Users/cpanato/code/src/github.com/falcosecurity/falcoctl …
```
> add some log messages to inform user when generating the tls certificates

- internal/follower/follower.go
/kind bug
/area library
When following a signed artifact the image ref for signing was incorrect and only contained the hash as in the following log
```
INFO   (ghcr.io/falcosecurity/rules/falco-rules:1) fetching descriptor from remote repository...
INFO   (ghcr.io/falcosecurity/rules/falco-rules:1) descriptor correctly fetched
INFO   (ghcr.io/falcosecurity/rules/falco-rules:1) found new version under tag "1"
INFO   (ghcr.io/falcosecurity/rules/falco-rules:1) pulling artifact from remote repository...
INFO   (ghcr.io/falcosecurity/rules/falco-rules:1) check if pulling an allowed …
```
> fix(follow): pass full repo+sha to the signature verification function

- pkg/output/output.go
/kind bug
> /kind design
/area cli
> /area tests
Output of the `artifact follow` command still contains colors even when the `--disable-styling` flag is present.
This PR removes the colors but still maintains "styling", which consists here in prepending each line with the log level and the artifact path.
Fixes #295 
This is a simple fix for the color issue I observed and encountered, …
> fix(cmd/artifact/follow): colored output despite `--disable-styling`

- cmd/artifact/info/info.go
- internal/follower/follower.go
- pkg/oci/authn/client.go
- pkg/oci/utils/utils.go
/kind bug
> /kind design
/area cli
> /area tests
Avoid caching authentication tokens in the client since they can expire. In those cases the client cannot invalidate the expired token, hence it will not have permission to access the resources.
Each time the client will acquire a new token based on it's configuration. Remember that this change does not affect the underlying credential helper's cache.
When we create the http client for a given repository …
> fix(follower): do not cache authentication tokens

- cmd/artifact/install/install.go
- internal/follower/follower.go
- pkg/oci/puller/puller.go
- pkg/oci/puller/puller_suite_test.go
- pkg/oci/puller/puller_test.go
/kind bug
> /kind design
/area library
/area cli
/area tests
Original errors are omitted when returning errors. Furthemore, tests have been added for the oci/puller package.
Fixes #
> fix(oci/puller): do not omit previous errors when returning them

- cmd/artifact/artifact.go
- cmd/artifact/config/config.go
- cmd/artifact/config/config_suite_test.go
- cmd/artifact/config/config_test.go
- cmd/artifact/config/doc.go
> /kind bug
> /kind design
/area cli
/area tests
Add a new command for artifacts: `falcoctl artifact config` which fetches the config layer for a given artifact.
```bash
❯ falcoctl artifact config falco-rules | jq
{
"name": "falco-rules",
"version": "2.0.0",
"requirements": [
{
"name": "engine_version",
"version": "26"
}
]
}
```
#332 
Fixes #
#332 
> new(cmd): add artifact config command

- cmd/artifact/config/config_suite_test.go
- cmd/artifact/install/install_suite_test.go
- cmd/registry/auth/basic/basic_suite_test.go
- cmd/registry/auth/oauth/oauth_suite_test.go
- cmd/registry/pull/pull_suite_test.go
- cmd/registry/push/push_suite_test.go
- pkg/oci/pusher/pusher_suite_test.go
> /kind bug
> /kind design
/kind flaky-test
> /area cli
/area tests
Fixes the failure of some tests caused by race conditions. Tests that interacts with a `registry` wait for it until it accepts connections.
Fixes #
> fix(tests): wait for registry to accept connections before running tests

- build/Dockerfile
/kind bug 
> /kind design
/area library
> /area cli
> /area tests
**What this PR does / why we need it**: upgrades alpine in dockerfile from 3.18.3 to 3.18.4 to patch a go vulnerability then upgrades and patches libssl3 and libcrypto3
**Which issue(s) this PR fixes**:344
Fixes #344 
**Special notes for your reviewer**: please let me know if i messed up formatting somewhere as this is my first pr here
> bugpatching issue 344 vulnerabilities including GHSA-m425-mq94-257g

- cmd/artifact/config/config.go
- cmd/artifact/config/config_test.go
- cmd/artifact/install/install.go
- cmd/artifact/install/install_test.go
- internal/follower/follower.go
- pkg/oci/puller/puller.go
- pkg/oci/puller/puller_test.go
> /kind bug
> /kind design
/kind feature
/area library
/area cli
/area tests
The `artifact config` now accepts the platform for which to fetch the config layer.
Fixes #
> feat(artifact/config): fetch config layer for a specific platform

- cmd/artifact/config/config_test.go
> /kind bug
> /kind design
> /area cli
/area tests
Add tests for the newly added flag `--platform` in the `artifact config` cmd.  
See #349. 
Fixes #
> tests(artifact/config): add new tests for the --platform flag

- cmd/artifact/artifact.go
- cmd/artifact/manifest/doc.go
- cmd/artifact/manifest/manifest.go
- cmd/artifact/manifest/manifest_suite_test.go
- cmd/artifact/manifest/manifest_test.go
- pkg/oci/puller/puller_suite_test.go
It allows to fetch the manifest for a given artifact based on it's platform.
> /kind bug
> /kind design
/kind feature
/area library
/area cli
/area tests
Add a new command for artifacts: `falcoctl artifact manifest` which fetches the manifest layer for a given artifact.
```bash
❯ falcoctl artifact manifest k8saudit --platform linux/arm64 | jq
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"config": {
"mediaType": …
```
> new(artifact/manifest): add manifest command

- go.mod
- go.sum
- pkg/driver/type/bpf.go
/kind cleanup
/area library
Mount `/sys/kernel/debug` can fail in lots of circumstances; for example if it is already mounted.
Since we don't always need it (indeed we only need it for x86_64 kernel releases between 4.14 and 4.17), just don't fail.
This is the same behavior that the old falco-driver-loader had: https://github.com/falcosecurity/falco/blob/master/scripts/falco-driver-loader#L628.
Also, bumped driverkit library to v0.16.0 (latest release).
Fixes #
> chore(pkg/driver): do not fail if /sys/kernel/debug fails to be mounted.

- cmd/driver/config/config.go
- cmd/driver/config/config_suite_test.go
- cmd/driver/config/config_test.go
- cmd/driver/printenv/printenv.go
- internal/config/config.go
- pkg/options/driver.go
/kind cleanup
/area cli
/area tests
Fixes #
> new(cmd/driver,pkg/options,internal/config): added `driver config` cmd tests

- cmd/driver/cleanup/cleanup.go
- cmd/driver/config/config.go
- cmd/driver/config/config_test.go
- cmd/driver/driver_linux.go
- cmd/driver/install/install.go
- cmd/driver/printenv/printenv.go
- internal/config/config.go
- pkg/options/driver.go
/kind cleanup
/area library
/area cli
This way all driver commands can customize their run with both CLI args or env variables, without actually storing anything in the config file.
Fixes #
> cleanup(cmd,internal,pkg): move `driver config` options to be common to all `driver` commands

- cmd/artifact/install/install.go
- cmd/driver/cleanup/cleanup.go
- cmd/driver/driver_linux.go
- cmd/driver/install/install.go
- main.go
- pkg/driver/distro/distro.go
- pkg/driver/type/bpf.go
- pkg/driver/type/kmod.go
- pkg/driver/type/type.go
/kind feature
/area library
/area cli
Fixes #
> new(cmd,pkg/driver): properly use a spinner for long operations.

- cmd/driver/config/config.go
> fix(cmd/driver): fixed segfault in driver config command.

- cmd/driver/install/install.go
- pkg/driver/type/bpf.go
- pkg/driver/type/kmod.go
- pkg/driver/type/modernbpf.go
- pkg/driver/type/type.go
/kind bug
/area library
/area cli
Also, avoid mounting /sys/kernel/debug in bpf `Cleanup` method, since it makes no sense. It is actually part of the `Build`.
Fixes #
> fix(pkg,cmd): eBPF probe must be symlinked under /root/.falco/falco-bpf.o

- cmd/driver/printenv/printenv.go
- pkg/driver/distro/distro.go
- pkg/driver/distro/flatcar.go
- pkg/driver/distro/flatcar_test.go
/kind bug
/area library
Moreover, call `return f.generic.FixupKernel(kr)` in flatcar FixupKernel.
Fixes #372 
> fix(pkg/driver): do not call FixupKernel when building drivers.

- .github/dependabot.yml
- .github/workflows/docker-image.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
/kind cleanup
- add dependabot config and update golangci-lint
/assign @leogr @LucaGuerra 
xref: https://github.com/falcosecurity/evolution/issues/339
> add dependabot config and update golangci-lint

- cmd/driver/cleanup/cleanup.go
- cmd/driver/install/install.go
/kind cleanup
/area cli
Fixes #
> chore(cmd): fixed up some strings.

- pkg/driver/distro/flatcar.go
/kind bug
/kind cleanup
/area library
Fixes building kernel module on Flatcar. The bash script that was relocating the kernel tools had some issues.
It was taken straight from the old driver loader bash script, but now it's a separate script, so some constructs like `local` make no sense there. A result was that no kernel tools were patched, thus they could fail to run if they were built against a newer glibc than the one provided by the falco-driver-loader image.
Also print the output of the script unconditionally, so we may have some idea about what's going on here.
I hope that …
> pkg/driver/flatcar: Update the script

- pkg/driver/distro/generic.go
- pkg/driver/distro/generic_test.go
- pkg/driver/distro/ubuntu.go
/kind bug
/area library
This PR fixes an issue with the `fixupKernel` method on the `generic` distro receiver, porting it to use same logic as the old falco-driver-loader script: https://github.com/falcosecurity/falco/blob/1b62b5ccd1c64cd972ef0252262075cbf42a130c/scripts/falco-driver-loader#L713
Fixes #
> fix(pkg/driver): fixed generic kernelversion fixup method.

- cmd/driver/install/install.go
- cmd/driver/install/install_test.go
- pkg/driver/distro/distro.go
> /kind bug
> /kind design
/kind feature
/area cli
> /area tests
Added option to add headers in the http GET request for the driver download
Option had been possible via environment variables in the script based download but is not possible anymore since the falcoctl migration
Fixes #426
example flag (for testing):
--http-headers="x-emc-namespace: default,Proxy-Authenticate: Basic"
> new(cmd/driver): support user provided headers option for driver download

- .github/workflows/release.yaml
> /kind bug
> /kind design
> /area cli
> /area tests
Add provenance for docker images stored in ECR registry.
Fixes #
> new(CI): add provenance for ecr image

- .github/workflows/release.yaml
/kind bug
> /kind design
> /area cli
> /area tests
This PR fixes the `release workflow` by using the aws ecr credentials when pushing the provenance
Fixes #
> fix(CI): properly get credentials for amazon ecr registry

- pkg/driver/type/kmod.go
Fixes #457
/kind bug
> /kind design
/area cli
> /area tests
This removes an extra '$' that was preventing the build process from reading the build log on failure. 
Fixes #457
Hope this helps!
> Remove extra '$' character.

- cmd/registry/push/push.go
- cmd/registry/push/push_suite_test.go
- cmd/registry/push/push_test.go
- go.mod
- go.sum
- pkg/test/data/rules.yaml
- pkg/test/data/rulesWithoutReqAndDeps.yaml
- pkg/test/filesystem.go
When the user does not provide requirements and dependencies when pushing a rulefile artifact, it will try to parse the rulefile and automatically set them in the config layer. It only supports files in .yaml format.
> /kind bug
> /kind design
/kind feature
/area cli
/area tests
feat(cmd/push): parse requirements and deps from rulesfile
When the user does not provide requirements and dependencies
when pushing a rulefile artifact, it will try to parse the
rulefile and …
> feat(cmd/push): parse requirements and deps from rulesfile

- cmd/registry/push/push.go
- internal/utils/compress.go
/kind bug
> /kind design
/area cli
> /area tests
When pushing multiple plugins we need to remove the temporary dirs created when compressing them. This commit implements a fix that tracks all the temporary dirs created at runtime and removes them at the end.
Fixes #
> fix(registry/push): correctly remove temporary dir

- cmd/driver/cleanup/cleanup_test.go
- cmd/driver/config/config_test.go
- cmd/driver/driver_linux.go
- cmd/driver/driver_others.go
- cmd/driver/install/install.go
- cmd/driver/install/install_test.go
- cmd/driver/printenv/printenv.go
- cmd/driver/printenv/printenv_test.go
- go.mod
- go.sum
- internal/config/config.go
- pkg/driver/distro/cos.go
- pkg/driver/distro/distro.go
- pkg/driver/distro/generic.go
- pkg/driver/kernel/kernel_linux.go
- pkg/driver/kernel/kernel_others.go
- pkg/driver/type/bpf.go
- pkg/driver/type/kmod.go
- pkg/driver/type/modernbpf.go
- pkg/driver/type/type.go
- pkg/options/driver.go
/kind feature
when a 
/area library
/area cli
This PR expands the driver automatic selection logic, in this way:
* `--type` CLI option/`type` config key/`FALCOCTL_DRIVER_TYPE` env var do now support multiple driver types to be specified
* if a single `type` is specified, we retain the old behavior
* when multiple `type`s are passed, the automatic selection logic will choose the best-fit given:
* types are passed in decreasing priority order
* driver must be supported on the machine
New default is to enable all drivers in this order: `modern_ebpf,ebpf,kmod`.
`COS` target does now specialize `PreferredDriver` method since it does not support `kmod`.
**Which issue(s) …
> new: driver selection logic

- README.md
This PR advertises the fact that `falcoctl` can easily be installed via the `Homebrew` package manager
Fixes #494
> chore(docco): Add Homebrew as a MacOS install option

- pkg/driver/distro/distro.go
/kind bug
/kind cleanup
/area library
This PR fixes the templating of kernel headers download script from driverkit, that needs a fixed up kernelversion (only ubuntu uses it in driverkit, and it must be actually fixed, so that eg: `#26~22.04.1 Ubuntu...`  becomes `26~22.04.1`).
~~Moreover, it bumps driverkit to what will become v0.18.2 that contains a fix for new KERNELDIR mechanism (https://github.com/falcosecurity/driverkit/pull/330).
`wip` until driverkit v0.18.2 is released.~~ Already in falcoctl main!
Fixes #
> fix(pkg/driver): fixup kernel headers download

- cmd/artifact/info/info.go
/kind bug
> /kind design
/area cli
> /area tests
It does not print the signature tags for the artifacts.
Before:
```bash
❯ falcoctl artifact info k8saudit
REF                                             TAGS
ghcr.io/falcosecurity/plugins/plugin/k8saudit   latest, 0, 0.5, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6, 0.6.0, sha256-7081acb636b9017850a4cdea58c3ecf2cde09b426da21a72fdfb434d1ff8ba76.sig, sha256-2497cdd0531d8927b736729c4d891bbc61f451445f378ceef74f21267552389 …
```
> fix(artifact/info): filter out signature tags

- internal/config/config.go
/kind bug
/area cli
This PR will fix the issue #519 by adding the missing 'backend' field when generating the default configuration
old : 
```yaml
indexes:
- name: falcosecurity
url: https://falcosecurity.github.io/falcoctl/index.yaml
```
new: 
```yaml
indexes:
- name: falcosecurity
url: https://falcosecurity.github.io/falcoctl/index.yaml
backend: "https"
```
Fixes #519
huge thanks to the contributors to the Falco project and its ecosystem.
> fix: Add backend 'https' to default index

- README.md
- cmd/registry/push/push.go
- cmd/registry/push/push_rulesfiles_test.go
- cmd/registry/push/push_test.go
- pkg/options/artifact.go
> /kind bug
> /kind design
/kind feature
/area cli
> /area tests
This PR introduces a new boolean arg for `registry push`: `--add-floating-tags`. If set, with `--version=1.2.3`, the tags `1` and `1.2` and `1.2.3` will be added automatically, it will make easier to follow the semver.
@alacuku do you think we should also add `latest` with that arg or another?
Fixes #
> add new boolean arg for 'registry push' --add-floating-tags, it will auto add the tags for the major and the minor versions

- pkg/enum/doc.go
- pkg/enum/enum.go
- pkg/enum/enum_test.go
- pkg/options/common.go
- pkg/options/driver.go
- pkg/output/logFormat.go
- pkg/output/logFormat_test.go
- pkg/output/logLevel.go
- pkg/output/logLevel_test.go
/kind cleanup
/area library
Moreover, moved logLevel and logFormat enums under pkg/output.
Fixes #
> cleanup(cmd,pkg): moved `enum` to its own package.

- cmd/driver/install/install.go
/kind cleanup
/area cli
Both `driverkit` and `falcoctl` logs a successful driver build. Remove the redundant falcoctl log; see attached screenshot: 
Fixes #
> chore(cmd/driver): remove redundant log.

- cmd/artifact/install/constants.go
- cmd/artifact/install/install.go
- cmd/artifact/install/install_test.go
/kind failing-test
/kind feature
/area cli
This PR adds a `--platform` CLI option to the `artifact install` command.
For example: `falcoctl artifact install --platform linux/amd64 ...`
There are various other commands that accept a `--platform` argument so I implemented this in the same way.
Reason: We are deploying Falco into environments that may be air gapped so we want to produce a single OCI image with the appropriate rule sets and plugins. We want to use `falcoctl` to download the artifacts. However, this always downloads the artifacts for the architecture that the CI system (or developer laptop) is running, and this often produces errors, e.g. "unable to …
> feat: Add --platform option to artifact/install

- README.md
- pkg/index/fetch/fetch.go
- pkg/index/fetch/file/doc.go
- pkg/index/fetch/file/fetcher.go
- pkg/index/fetch/file/fetcher_test.go
/kind feature
This PR adds a "local file" storage backend for the index file.
To keep consistent with the existing design, this is specified by `file:///some/directory/my-index.yaml` which allows the existing code to correctly guess the storage backend.
I wrote a test covering the new backend as well.
Reason we need this: We want to use `falcoctl` in environments to help build configuration artifacts in environments that may not have internet access, so a local file works better for us.
Fixes #
> feat: Add file backend to fetcher

- cmd/driver/config/config.go
- internal/config/config.go
/kind bug
/kind cleanup
/area cli
This PR enables the `namespace` parameter of `driver config` command to be passed as `FALCOCTL_DRIVER_CONFIG_NAMESPACE` env variable.
Also, it fixes k8s configMap commit code, switching from `Patch` to `Update` command.
Finally, logs are a little improved.
Fixes #
> new(cmd/driver): driver config namespace from env variable

- pkg/driver/distro/distro_test.go
- pkg/driver/distro/oracle.go
/kind cleanup
/area library
https://github.com/falcosecurity/falcoctl/pull/356 removed a check about `uek` kernels while building kmod: https://github.com/falcosecurity/falcoctl/pull/356/files#diff-5f5269945d03266c023f8eff0f114f39d68d0fec1bcc9b57f386e309630f9db9L186.
This PR restores the check by avoiding to allow `kmod` type for `uek` kernels.
Fixes #
> chore(pkg/driver): restored `uek` kernel check.

- cmd/registry/push/push.go
- internal/utils/compress.go
- internal/utils/compress_test.go
- pkg/driver/type/modernbpf.go
/kind bug
> /kind design
/area library
/area cli
/area tests
A `registry push` command like:
```
falcoctl registry push
--type plugin --version 0.1.1 
--requires plugin_api_version:3.1.0 
--platform linux/amd64
ghcr.io/alacuku/plugins/plugin/k8smeta:0.1.1 
/home/aldo/Downloads/libk8smeta.so 
```
works fine, but when we try to install that artifact we get the following:
```
falcoctl artifact install ghcr.io/alacuku/plugins/plugin/k8smeta:0.1.1
2024-07-24 15:57:15 INFO …
```
> fix(push): use basename for artifacts when compressed in tar.gz

- .goreleaser.yml
> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #
> update(.goreleaser): bump version to v2

- cmd/registry/auth/basic/basic.go
/kind bug
> /kind design
/area cli
> /area tests
Binding pflags to Viper too early will generate a faulty configuration file for falcoctl. This commit ensures binding is done only when the basic authentication command is called.
Fixes #
> fix(auth/basic): bind pflags to viper only when required

- cmd/driver/config/commit_test.go
- cmd/driver/config/config.go
- cmd/driver/config/config_test.go
- go.mod
- internal/config/config.go
/kind bug
> /kind design
/area cli
/area tests
When running in kubernetes, falcoctl does not update the falco config map but creates a new
specialized config file with the selected engine kind. The command expects the name of the Falco
configmap from which to read the Falco configuration. This is needed to avoid conflicts when multiple
Falco's are deployed in the same cluster and namespace. Just to let you know, these are breaking changes.
The engine …
> update(driver/config)!: use the same logic to configure engine kind for different enviroments

- go.mod
- go.sum
- pkg/driver/distro/cos.go
/kind cleanup
/area library
Moreover, removed useless line in cos distro.
Fixes #
Driverkit v0.20.3 contains a fix for the kernelrelease regex (https://github.com/falcosecurity/driverkit/pull/355) that will fix COS kernelreleases (eg: `5.10.8+`) being failed to be matched and thus remaining empty (https://github.com/falcosecurity/falco/issues/3278).
> update(go,pkg): updated driverkit to v0.20.3.

- cmd/driver/config/config.go
/kind bug
> /kind design
/area cli
> /area tests
Falco config files are not supposed to contain sensitive information, so read permissions are given to all users. With this fix, the permissions of the config file for the driver engine override will be aligned to other Falco configs files under `/etc/falco`.
The issue was discovered with falcoctl 0.10, which is bundled with Falco 0.39 …
> fix(cmd): relax file perms for Falco driver config override

- pkg/oci/repository/repository.go
/kind bug
/area library
When tags are paginated, we need to continuously append to our resulting slice instead of overwriting it.
Example output before:
```
./falcoctl artifact info cloudtrail-rules --config=config.yaml 
REF                                             	TAGS
ghcr.io/falcosecurity/plugins/ruleset/cloudtrail	
```
Example output after:
```
./falcoctl artifact info cloudtrail-rules --config=config.yaml 
REF                                             	TAGS
ghcr.io/falcosecurity/plugins/ruleset/cloudtrail	latest, 0, 0.7, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8, 0.8.0, 0.9, 0.9.0, 0.9.1, 0.10, 0.10.0, 0.11, 0.11.0, main, 0.12, 0.12.0, 0.12.1, 0.12.2, 0.12.3
``` …
> fix(pkg/oci): fix Tags pagination support.

- internal/login/gcp/gcp.go
- pkg/oci/authn/gcp.go
Adjusted OAuth scope to `https://www.googleapis.com/auth/cloud-platform` for compatibility with both service account and Workload Identity setups, resolving invalid scope errors when accessing Artifact Registry.
> /kind bug
> /kind design
> /area cli
> /area tests
This PR fixes an issue with OAuth authentication when accessing Google Artifact Registry using a service account. By ensuring the correct scope (https://www.googleapis.com/auth/cloud-platform) …
> fix(auth/gcp): ensure correct OAuth scope for Artifact Registry with service account

- internal/follower/follower.go
- internal/follower/follower_test.go
- internal/utils/extract.go
/kind bug
/area cli
A bit of background on my use-case:
I've configured Falco to load all rules from a given sub-directory within `/etc/falco`, e.g.: `/etc/falco/subdir/rules1.yaml`, and packaged multiple rules files into separate `rulesfile` artifacts in `tar.gz` format.
During packaging, I'll generate the final directory structure I want and archive it, knowing that `falcoctl artifact` will extract the contents onto `/etc/falco`.
The issue is that while `falco artifact install` works great, `falco artifact follow` seems to break when processing the file path as it expects base paths to always be files, so it'll always fail when the rules gets updated and then it …
> fix(follow): handle directories in tar.gz artifacts
