falcosecurity/falcoctl

OWNERS

Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
Fixes #4
```release-note
setup OWNERS file
```

new: owners for falcoctl

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/failing-tests.md
.github/PULL_REQUEST_TEMPLATE.md

This PR adds issue and pull-request templates.
```release-note
NONE
```

doc: issue and pull request template

---

OWNERS

Co-authored-by: Lorenzo Fontana <lo@linux.com>
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
NONE
NONE
```release-note
NONE
```

update(OWNERS): adding leodido and fntlnz to approvers

---

LICENSE

Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
NONE
Fixes #12
```release-note
new: apache 2.0 license
```

new: apache 2.0 license (fixes #12)

---

kubernetes/audit.go

/kind cleanup
NONE
NONE
```release-note
NONE
```

Fixing error

---

OWNERS

Actively contributing to the tool now.
> /kind bug
/kind cleanup
> /kind design
> /area cli
> /area tests
Fixes #
```release-note
Add mstemm as reviewer/approver.
```

Add mstemm as reviewer/approver

---

release.md

/kind cleanup
NONE
We are not going to release docker images for falcoctl.
NONE
```release-note
NONE
```

fix: not releasing docker images for falcoctl

---

pkg/converter/psp/k8s_psp_rules_template.go

In the case where a psp does not have a falco-rules-psp-images
annotation that limits the images where the rules apply, the syscall
related rules were being applied to both hosts and containers.
Change this so the events are limited to containers.
This also required a few changes to put the evt.type restriction at the
beginning of the rule condition to avoid warnings about evt.types.
/kind bug
> /kind design
/area cli
> /area tests
**Which issue(s) this …

Limit syscall activity for psp rules to containers

---

cmd/probe_install_linux.go

/kind bug
/kind cleanup
/area cli
Improves and fixes the pre-run check for install probe command.
/cc @fntlnz 
```release-note
NONE
```

update: prerun check for install probe command

---

process/interface.go

Adding an interface.go for the new structure in proposal #44
Signed-off-by: Kris Nova <kris@nivenly.com>
> /kind bug
> /kind design
/kind feature
/area library
> /area cli
> /area tests
This creates the interfaces for the proposal defined in #44 
Fixes #
```release-note
Adding the `Process` interfaces and structs
```

Interface for processes

---

pkg/kubernetes/falco.go

/kind feature
> /area cli
> /area tests
This PR updates the cli to use apps v1 API instead of the apps v1beta2 API which was deprecated in 1.16.
Fixes #33
This technically resolves issue #33 as it specifically fixes the issue of creating a Daemonset. The note in that issue also mentions line 26 of this file (which actually references the RBAC APIs. While this isn't broken(yet), it does appear that those APIs will be deprecated within the next release. As long as this looks good, I have a followup PR ready for that. But …

Update appsv1beta2 -> appsv1

---

OWNERS

Adds @leogr to OWNERS file
NONE
```release-note
NONE
```

update: add leogr to OWNERS file

---

README.md

Signed-off-by: Kris Nova <kris@nivenly.com>
> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #
```release-note
docs: README
```

Adding basic README.md content

---

cmd/convert.go
cmd/convert_psp.go
cmd/delete.go
cmd/delete_falco.go
cmd/install.go
cmd/install_falco.go
cmd/install_probe.go
cmd/install_probe_linux.go
cmd/install_rule.go
cmd/install_rule_linux.go
cmd/install_tls.go
cmd/install_tls_linux.go
cmd/root.go
main.go

Signed-off-by: Suresh Palemoni <suresh.palemoni@gmail.com>
/kind cleanup
/kind feature
/area cli
Refactoring
https://github.com/falcosecurity/falcoctl/issues/57
Fixes #
PR for the issue: https://github.com/falcosecurity/falcoctl/issues/57.
```release-note
NONE
```

refactored cmd package inline with go idiomatic practices

---

cmd/install_probe_linux.go
cmd/install_tls_linux.go
cmd/root.go
pkg/cli/env.go
pkg/kubernetes/factory/factory.go
pkg/kubernetes/factory/matchversion.go
pkg/probeloader/loader.go
pkg/tls/generator.go

Signed-off-by: Suresh Palemoni <suresh.palemoni@gmail.com>
/kind cleanup
/kind feature
/area cli
https://github.com/falcosecurity/falcoctl/issues/57
Fixes #
https://github.com/falcosecurity/falcoctl/issues/57
```release-note
NONE
```

refactored pkg directory inline with go idiomatic practices

---

pkg/tls/generator.go

Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
This PR fixes the permission bits on directory created by `falcoctl install tls`.
/kind bug
> /kind design
/area library
> /area cli
> /area tests
Fixes #78 
```release-note
fix: correct permission bits for TLS directories
```

fix(pkg/tls): correct dir permission bits

---

OWNERS

After changing the github username from rajibmitra to rmitr - Rajib expressed that is very busy to donate time to this project in the near future. We are going to keep Rajib in the org of course but removing from maintainer duty. Rajib, you'll be welcome once you are ready to come back!
Co-Authored-By: Leonardo Di Donato <leodidonato@gmail.com>
Signed-off-by: Lorenzo Fontana <lo@linux.com>
> /kind bug
> /kind design
Fixes #
**Does this PR introduce a user-facing …

update: remove rajibmitra from OWNERS

---

cmd/root.go

Signed-off-by: Andrea Bonanno <andrea@bonanno.cloud>
/kind feature
/area cli
Improves Falcoctl config location structure, so future Falcoctl internal files can be grouped under the same directory.
Fixes #
```release-note
NONE
```

update: config file in dedicated directory

---

cmd/repo.go
cmd/repo_add.go
cmd/repo_remove.go
cmd/root.go
cmd/testdata/help.txt
cmd/testdata/noargsnoflags.txt
cmd/testdata/wrongflag.txt
pkg/repo/types.go

/kind feature
/area cli
This PR complements #106, adding the `repo remove` command. 
Fixes #
This PR depends on #106 
```release-note
new: repo remove command
```

Repo remove

---

cmd/install_tls_linux.go
cmd/root.go

> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #
```release-note
NONE
```

Bug #114 Fixed -- > Country and Config have same shorthand

---

cmd/testdata/help.txt
cmd/testdata/noargsnoflags.txt
cmd/testdata/wrongflag.txt

```
```
> /kind bug
> /kind design
/kind failing-test
> /area cli
/area tests
Update tests with the new commands added to falcoctl.
Fixes #
```release-note
NONE
```

update(tests): fix broken tests

---

.github/PULL_REQUEST_TEMPLATE.md

```
```
> /kind bug
> /kind design
> /area cli
> /area tests
Remove the release notes section from the PR template.
Fixes #
```release-note
NONE
```

chore(docs): remove release notes section from PR template

---

.github/workflows/lint.yaml
.golangci.yml

```
```
> /kind bug
> /kind design
> /area cli
> /area tests
This PR adds linting to the CI. 
Fixes #

feat(CI): add linting

---

Makefile
cmd/cli_test.go
cmd/config_options.go
cmd/delete.go
cmd/delete_falco.go
cmd/install.go
cmd/install_falco.go
cmd/install_rule.go
cmd/install_rule_linux.go
cmd/install_tls.go
cmd/install_tls_linux.go
cmd/interfaces.go
cmd/internal/validate/isfilepath.go
cmd/internal/validate/islogruslevel.go
cmd/internal/validate/isregistryurl.go
cmd/internal/validate/validate.go
cmd/list.go
cmd/list_repo.go
cmd/repo.go
cmd/repo_add.go
cmd/repo_remove.go
cmd/root.go
cmd/search.go
cmd/search_registry.go
main.go
pkg/registry/types.go
pkg/repo/types.go
pkg/tls/generator.go
process/interface.go

```
```
> /kind bug
/kind cleanup
> /kind design
/area library
/area cli
> /area tests
This PR adds some new targets to the `Makefile`:
* fmt target: make sure that all files are formatted, have the license header (if not adds it), checks that the package imports are in order and that go mod and sum are tidied.
* lint target: runs golangci-lint against the modified files. Handy to check the modified code before pushing it.
Further more …

chore format license header

---

Makefile

```
```
> /kind bug
> /kind design
> /area cli
> /area tests
Updating the `lint` target in Makefile to use  "--new-from-rev master". It shows the new issues created after git revision "master".
Fixes #

update(Makefile): lint all files changed from the master branch

---

cmd/testdata/help.txt
cmd/testdata/noargsnoflags.txt
cmd/testdata/wrongflag.txt

```
```
> /kind bug
> /kind design
/kind failing-test
> /area cli
/area tests
This PR updates tests broken by #125 .
Fixes #

fix(tests): fix output tests

---

.github/workflows/integration.yaml
.goreleaser.yml

```
```
> /kind bug
> /kind design
> /area cli
> /area tests
This PR updates the `.goreleaser.yml configuration file to build the falcoctl for the following operating systems and architectures:
- operating systems: linux, darwin, and windows;
- archs: amd64, arm64, and 386.
Furthermore, the CI has been updated to use `goreleaser` when building the binary in the `integration-pipeline` workflow.
**Which issue(s) …

update(goreleaser): use goreleaser when building falcoctl

---

.github/workflows/release.yaml
.goreleaser.yml

> /kind bug
> /kind design
> /area cli
> /area tests
Add the `release` CI workflow.
Fixes #

new(CI): add the release CI workflow

---

pkg/oci/pusher/pusher.go

Fetch only the index data instead of the full graph pointed by the index which is what the copy function in ORAS does. Using the FetchReference function instead.
Co-authored-by: Lorenzo Susini <susinilorenzo1@gmail.com>
/kind bug
> /kind design
/area library
/area cli
> /area tests
This PR fixes a bug that caused `falcoctl` to download the full artifact when only the `image index` data were needed.
**Which issue(s) this PR …

fix(pusher): retrieve only the index and not all the layers

---

OWNERS

Following up the discussion in https://github.com/falcosecurity/falcoctl/issues/136 and in the last community call, this PR **opens the voting** for the addition of new approvers and reviewers (although we would not need a formal vote for reviewers).
For this kind of decision, a simple majority vote among core maintainers (cc @falcosecurity/core-maintainers) is enough to proceed with the changes (see: https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#majority-vote). Whoever is subject to the changes proposal is not eligible for voting (@zuc, @maxgio92, @cpanato, @FedeDP).
**Voting deadline**: 2022-09-15
Close #136

vote: update(OWNERS): add new maintainers and reviewers

---

cmd/artifact.go
cmd/artifact_search.go
cmd/index.go
cmd/index_add.go
cmd/index_list.go
cmd/index_remove.go
cmd/index_update.go
cmd/root.go
cmd/testdata/help.txt
cmd/testdata/noargsnoflags.txt
cmd/testdata/wrongflag.txt
go.mod
pkg/index/config.go
pkg/index/constants.go
pkg/index/doc.go
pkg/index/fetch.go
pkg/index/index.go
pkg/output/output.go

> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
This PR introduces the commands that can be used to manage indexes, as per the proposal in https://github.com/falcosecurity/falcoctl/pull/143
Moreover, also the `artifact search` command was implemented so that I had a quick and dirty way to test the search functionality that was already implemented in the library. 
Subsequent PRs will implement proper testing for the newly introduced library. 
Lastly, I …

new: introduce index related commands

---

cmd/registry_push.go
pkg/oci/pusher/pusher.go
pkg/options/artifact_options.go
pkg/output/output.go
pkg/output/tracker.go

> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
Add support for a tracker interface in the pusher and puller libraries. It allows to define a custom tracker that gives information about the ongoing pull and push operations.
Using the new tracker interface the `push` command shows the progress of the push operations using a progress bar:
```bash
❯ ./falcoctl registry push --type plugin cloudtrail-0.3.0-linux-x86_64.tar.gz  ghcr.io/alacuku/cloudtrail:latest …
```

new(cmd/push): add progress bar while pushing artifacts

---

.github/workflows/integration.yaml

> /kind bug
> /kind design
> /area cli
> /area tests
This PR changes the branch name from `master` to `main` in the integration workflow.
Fixes #

update(CI): change branch name from master to main in the integration workflow

---

README.md

Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #

Create README.md for `gh-pages`

---

Makefile

/kind bug
/area library
#153 Follow-up
Fixes #

build(Makefile): correct default branch

---

cmd/artifact_search.go
pkg/index/index.go

/kind feature
/area library
Add the ability to read an index from a local file. Particularly helpful for the CI.
Fixes #

new(pkg/index): read an index from file

---

README.md
proposals/20220916-rules-and-plugin-distribution.md

Co-authored-by: Aldo Lacuku <aldo@lacuku.eu>
Co-authored-by: Lorenzo Susini <susinilorenzo1@gmail.com>
Co-authored-by: Luca Guerra <luca@guerra.sh>
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
See #136 

docs(proposal): Falco Rules and Plugin distribution

---

cmd/registry_push.go
pkg/artifact/artifact.go
pkg/artifact/artifact_test.go
pkg/artifact/doc.go
pkg/oci/pusher/pusher.go
pkg/oci/types.go
pkg/oci/types_test.go
pkg/options/artifact_options.go

> /kind bug
/kind cleanup
/kind design
/kind feature
/area library
/area cli
> /area tests
This allows full support for https://github.com/falcosecurity/falco/pull/2190
Fixes #
Not yet sure if `|` is a good symbol to express the "OR" meaning. Apparently yes, but one can be in trouble when using it in a shell command. Anyway, we can change it later.

refactor: dependencies types

---

pkg/artifact/artifact.go
pkg/oci/types.go

> /kind bug
/kind cleanup
> /kind design
/area library
> /area cli
> /area tests
Fix a couple of types as suggested in #157.
Fixes #

chore(pkg): fix a couple of typos

---

cmd/registry_pull.go
cmd/registry_push.go
go.mod
go.sum
pkg/oci/constants.go
pkg/oci/puller/puller.go
pkg/oci/pusher/options.go
pkg/oci/pusher/pusher.go
pkg/options/artifact_options.go

> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
While reasoning about using the `push` command we identified a problem. 
Basically, one of the uses of this command is in CI. In the case of plugins, having a push command that retrieves the fat manifest and modifies it before pushing it again opens up a race condition when multiple push operations are performed concurrently. The best way to avoid this is to push the artifacts that needs a fat manifest …

refactor push command

---

cmd/registry_pull.go
pkg/oci/puller/puller.go
pkg/oci/types.go
pkg/options/artifact_options.go

> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
This PR removes the need to specify a type when pulling artifacts. It is not necessary since we can infer the type by using media types. 
This PR will unblock the one opened in wip for the `install` command.
Fixes #

update: remove type from pull operations

---

pkg/oci/pusher/pusher.go

> /kind bug
/kind cleanup
> /kind design
/area library
> /area cli
> /area tests
Remove unused code from the pusher package.
Fixes #

chore(pkg): remove dead code

---

cmd/artifact.go
cmd/artifact_install.go
cmd/artifact_search.go
cmd/internal/utils/extract.go
cmd/internal/utils/indexes.go
cmd/internal/utils/validate.go
go.mod
pkg/index/index.go
pkg/oci/puller/puller.go
pkg/oci/types.go

> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
This PR implements the `artifact install` command.  This command is basically implemented starting from the already available operations on index files and the functionalities offered by the puller. 
Fixes #

new: implement artifact install command

---

cmd/artifact_install.go

> /kind bug
> /kind design
/area cli
> /area tests
Just fixing a simple comment. 
Fixes #

chore(cmd): fix comment about artifact install

---

cmd/artifact.go
cmd/artifact_info.go
pkg/oci/tags.go
pkg/output/output.go

> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
This PR implements the `artifact info` command. It can be used to retrieve all the available versions of an artifact from a given repository. 
Currently on wip because it uses a utility function to get all indexes, defined in the `artifact install` PR. Once that is merged, the wip will be removed.
Fixes #

new: introduce artifact info command

---

cmd/registry_push.go
pkg/oci/pusher/options.go
pkg/oci/pusher/pusher.go
pkg/oci/pusher/pusher_test.go
pkg/options/artifact_options.go

> /kind bug
> /kind design
/kind feature
/area library
/area cli
> /area tests
This PR let the pusher be able to add annotation source to indexes and manifests.
This is needed by GHCR to correctly publish artifacts.
Fixes #

new: add annotation source for GHCR

---

pkg/output/output.go

> /kind bug
> /kind design
/area library
> /area cli
> /area tests
Add methods to the printer in order to set the `scope`, and ` writer` for an existing printer. It also adds two methods disable or enable the styling after the printer has been created. 
Fixes #

update(output): add new methods to the printer

---

.github/workflows/docker-image.yaml

> /kind bug
> /kind design
> /area cli
> /area tests
Add floating tags to docker image based on major and minor version numbers of a release
Fixes #

update(CI): add floating tags to docker image based on major and minor version numbers of a release

---

pkg/oci/puller/puller.go
pkg/oci/repository.go

/kind bug
> /kind design
/area library
> /area cli
> /area tests
Use functional options to create repo and fix the current main branch. 
Fixes #

fix(pkg): create repo with functional options and fix main branch error 

---

internal/registry/login/login.go
internal/utils/registry.go

> /kind bug
/kind cleanup
> /kind design
/area library
/area cli
> /area tests
Improve error messages so that we can better understand what went wrong. 
Fixes #

chore: improve error messages in Login and ClientForRegistry

---

internal/registry/push/push.go

> /kind bug
> /kind design
/area cli
> /area tests
Fix short description of push command. 
Fixes #

docs: switch ref and file in push short usage

---

cmd/artifact.go
internal/artifact/list/artifact_list.go
internal/artifact/list/doc.go
internal/artifact/search/artifact_search.go

/kind feature
/area cli
I wanted to list all the rulesfile artifacts in the index and couldn't do it, so I added an option to do just that :)
Fixes #

new(cmd): add artifact search --type, add artifact list (by index and/or type)

---

pkg/oci/pusher/pusher.go

/kind bug
> /kind design
/area library
> /area cli
> /area tests
While pushing, we create temporary files that eventually need to be deleted. Make use of a temporary directory to remove them all. 
Fixes #

fix: correctly remove temp files when pushing

---

internal/registry/push/push.go
internal/utils/validate.go
pkg/oci/pusher/options.go
pkg/oci/pusher/pusher.go
pkg/oci/pusher/pusher_test.go
pkg/oci/types.go
pkg/options/artifact_options.go

> /kind bug
> /kind design
/kind feature
> /area cli
> /area tests
This PR aims to improve the artifact model to accommodate the dep manager's needs which we will implement in a subsequent PR.
Fixes #

preparation for artifact dep management

---

pkg/oci/types.go

> /kind bug
> /kind design
/area library
> /area cli
> /area tests
Fix typo.
Fixes #

chore(pkg/oci): fix typo in function name

---

pkg/oci/types.go

/kind bug
> /kind design
/area library
> /area cli
> /area tests
This PR adds the possibility to also set the `alternatives` for a dependency when setting it in the `artifact` config.
Fixes #
This PR includes also the #202 .

 fix(pkg/ogi): allow the alternatives when setting a dependency in the artifact config

---

go.mod
pkg/install/tls/generator.go
pkg/oci/authn/credentialstore.go
pkg/oci/pusher/pusher.go

> /kind bug
/kind cleanup
> /kind design
/area library
/area cli
> /area tests
Logrus was a left-over dependency that's no more needed with the current state of the project, since we now log using pterm.
Fixes #

chore: don't use logrus as logger

---

internal/artifact/follow/follow.go
internal/registry/pull/pull.go
internal/registry/push/push.go

> /kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
Use const for strings containing help for commands.
Fixes #

chore: use const when possible

---

internal/artifact/list/artifact_list.go

> /kind bug
> /kind design
/kind feature
/area cli
> /area tests
Add alias `ls` to artifact install. Aliases are already used for index management commands and are useful also in this case!
Fixes #

update: add alias ls to artifact list command

---

internal/index/add/index_add.go
internal/registry/pull/pull.go
internal/registry/push/push.go
internal/utils/credentials.go
internal/utils/registry.go

While trying out integration with helm chart we discovered some bugs that need to be fixed with this PR.
/kind bug
> /kind design
/area library
/area cli
> /area tests
Fixes #

fix: add fixes while trying to get a first version of helm chart working

---

internal/artifact/follow/follow.go
internal/config/config.go
internal/follower/follower.go

/kind bug
> /kind design
> /area cli
> /area tests
Adjust the way we check requirements since Falco returns all strings from its version endpoint
Fixes #

fix: falco is returning a string for all versions

---

internal/config/config.go

> /kind bug
> /kind design
/area library
> /area cli
> /area tests
Make sure the directory of the config file gets created if needed.
Fixes #

fix: create config file directory if needed

---

cmd/root.go

> /kind bug
> /kind design
> /area cli
> /area tests
Little PR to better describe the purpose of the tool.
Fixes #

docs: rename purpose of the tool

---

cmd/testdata/help.txt
cmd/testdata/noargsnoflags.txt

/kind bug
> /kind design
/area cli
> /area tests
Update test data with new description of the tool. I believe we have a problem in the CI: the PR that updated the description should have not be merged with failing tests. I will investigate more.
Fixes #

fix: update test data

---

cmd/testdata/help.txt
cmd/testdata/noargsnoflags.txt
cmd/testdata/wrongflag.txt
internal/config/config.go

> /kind bug
/kind design
/area cli
> /area tests
Change default location for config time to `/etc/falcoctl/falcoctl.yaml` (which is consistent with the Falco style, i.e., `/etc/falco/falco.yaml`).
Fixes #

refactor: config path

---

internal/artifact/follow/follow.go

Co-authored-by: Lorenzo Susini <susinilorenzo1@gmail.com>
/kind bug
> /kind design
/area cli
> /area tests
Correctly handle context cancellation when the follower enters in back off when retrieving the Falco versions.  
Fixes #

fix(follower): correctly handle context cancelation in follower

---

internal/follower/follower.go

Moreover, avoid shadowing `equal` method.
/kind cleanup
Fixes #

chore(internal): fixed a wrong log.

---

internal/utils/extract.go

/kind bug
> /kind design
/area library
> /area cli
> /area tests
Ensure no path traversal via tar archive.
https://github.com/falcosecurity/falcoctl/issues/221
Fixes #

fix: ensure extracted files are put inside dest dir

---

cmd/root.go

/kind bug
> /kind design
/area cli
> /area tests
"falcoctl version" results in a segmentation fault.
Fixes #

fix(cmd): SIGSEGV on "falcoctl version"

---

cmd/artifact/follow/follow.go
internal/follower/follower.go

/kind bug
> /kind design
/area cli
> /area tests
The follower retrievs the api versions from falco at start up. The api versions are used to check if an artifact is compatible with the running instance of falco. Here we expect falco to sent generic data, and we do not make assumptions on the data type when unmarshalling the received data.
Fixes #
**Special notes for your …

fix(follower): do not make assumptions on data retrieved from version endpoint

---

cmd/artifact/install/install.go
internal/config/config.go

> /kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
Using the `falcoctl artifact install` with no ref results in no error.
Fixes #
NONE

fix(internal): error handling with no artifacts

---

README.md
cmd/artifact/follow/follow.go
cmd/registry/pull/pull.go
cmd/root.go
cmd/testdata/help.txt
cmd/testdata/noargsnoflags.txt
internal/follower/follower.go

> /kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
Fixes #

chore: improve command line help messages

---

internal/config/config.go

> /kind bug
> /kind design
/area cli
> /area tests
This PR removes the default configuration for the "artifact follow" command. The configuration should be provided by the user.
Fixes #

update(config): remove follower's default config values

---

README.md
cmd/artifact/follow/follow.go
cmd/artifact/install/install.go

> /kind bug
/kind cleanup
> /kind design
> /area cli
> /area tests
The current README.md is outdated.
Fixes #
NONE

new documentation

---

README.md

> /kind bug
> /kind design
> /area cli
> /area tests
The documentation for the `falcoctl artifact follow` command was missing.
Fixes #
NONE

docs(README.md): added artifact follow documentation

---

README.md

> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #243
NONE

docs(README.md): added documentation of cache mechanism

---

cmd/root.go
cmd/testdata/help.txt
cmd/testdata/noargsnoflags.txt

> /kind bug
> /kind design
/area cli
> /area tests
Add a simple ascii art for the root command, just for fun :) 
Fixes #

doc: add simple ascii art

---

cmd/artifact/follow/follow.go

> /kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
Don't check if `every` and `cron` are both set by hand, let's do it with Cobra
Fixes #

update: use mark flags as mutually exclusive for cron and every

---

cmd/registry/push/push.go

/kind bug
> /kind design
/area cli
> /area tests
/area examples
Fixes #

fix(push.go): allow the push cmd to inform about the required flags

---

README.md

> /kind bug
> /kind design
> /area cli
> /area tests
Update the README title according to the description of the tool.
Fixes #

docs: update readme title according to description of root cmd

---

cmd/artifact/install/install.go

/area cli
/area examples
The description of the command showed examples of the follow command, instead of the install command.
The examples have been replaced with examples of the correct command.
Fixes #261 
NA

chore(cmd/artifact/install): fix description

---

.github/workflows/codeql-analysis.yaml
.github/workflows/docker-image.yaml
.github/workflows/integration.yaml
.github/workflows/lint.yaml
.github/workflows/release.yaml
.golangci.yml
.goreleaser.yml
Makefile
cmd/artifact/info/info.go
cmd/artifact/install/deps_test.go
cmd/artifact/install/install.go
cmd/artifact/list/artifact_list.go
cmd/artifact/search/artifact_search.go
cmd/cli_test.go
cmd/index/list/list.go
cmd/index/remove/remove.go
cmd/index/update/update.go
go.mod
internal/utils/registry.go
main.go
pkg/artifact/artifact_test.go
pkg/index/index_test.go
pkg/install/tls/generator.go
pkg/oci/authn/client.go
pkg/oci/authn/credentialstore.go
pkg/oci/pusher/pusher.go
pkg/oci/pusher/pusher_test.go
pkg/oci/registry/registry.go
pkg/output/output.go

/kind cleanup
/kind feature
- upgrade to use go1.20
- cleanup ci, adjust indentation, fix version comments and update hashes
Fixes https://github.com/falcosecurity/falcoctl/issues/269

Update go to 1.20 and cleanup ci job

---

cmd/index/update/update.go

Furthermore debug messages are printed when --verbose flag is set.
> /kind bug
> /kind design
/kind feature
/area cli
> /area tests
Add output messages for `falcoctl index update` command. The following snippet shows the outputs when running the command with `--verbose` flag set to true:
```bash
❯ falcoctl index update falcosecurity falcosecurity1 --verbose
INFO  Creating in-memory cache using indexes file "/home/aldo/.config/falcoctl/indexes.yaml" and indexes directory …
```

feat(index/update): add output messages for index update command

---

pkg/oci/puller/puller.go
pkg/oci/types.go

/kind cleanup
/area cli
This adds a more clear error message when trying to install a not allowed artifact type.
Fixes #266 

chore(oci): more clear error on wrong type

---

cmd/artifact/follow/follow.go
cmd/artifact/install/install.go
internal/follower/follower.go

/kind bug
/area cli
The directory existence and possibility to write is checked only if necessary.
Fixes #253 

fix: check directory existance iff necessary

---

cmd/registry/pull/pull.go

/kind bug
> /kind design
/area cli
> /area tests
This removes some old examples in the help message.
Fixes #

fix(cmd/registry/pull): updated help message

---

Makefile

/kind cleanup
/area tests
/area cli
Introduce clean make target to cleanup local build output.
NA
Furthermore, it adds declaration of targets which are phony as phony, and remove ones which are actual output files.

chore(makefile): add clean target and update phony targets

---

.github/workflows/docker-image.yaml
.github/workflows/release.yaml

> /kind bug
> /kind design
> /area cli
> /area tests
/kind feature
Fixes #

add slsa provenance for binaries and sign container images

---

go.mod
go.sum

> /kind bug
> /kind design
/area library
> /area cli
> /area tests
Bump `oras-go` library .
Fixes #

chore(falcoctl): bump oras-go to v2.2.0

---

cmd/artifact/follow/follow.go
cmd/artifact/install/install.go

> /kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
Removing leftover code in `install` & `follow` commands. The indexes are handled using the new in-memory cache introduced in #244 
Fixes #

cleanup(cmd): remove leftover code in install and follow commands

---

pkg/index/cache/cache.go

/kind bug
> /kind design
/area library
/area cli
> /area tests
Initialize the fetcher when the cache is created using the NewFromConfig func.
Fixes #

fix(cache): initialize the fetcher when creating the cache

---

README.md

update(readme): add links to the website and main falco repo

---

README.md

/area cli
The env variable `FALCOCTL_ARTIFACT_NOVERIFY` was not listed anywhere. It is used to skip signature verification (where supported).
Fixes #

update(docs): add FALCOCTL_ARTIFACT_NOVERIFY

---

Makefile

> /kind bug
> /kind design
> /area cli
> /area tests
It allows to run commands like: ` make clean && make falcoctl ` even when falcoctl binary does not exist.
Fixes #

update(Makefile): do not error if file does not exist when running clean target

---

Makefile

chore(Makefile): enforce SPDX license header in Makefile `fmt` target.

---

.github/workflows/release.yaml

/kind bug
/area cli
As per title. The older version appeared to depend on a version of cosign that is no longer available or recommended.
Fixes #

update(gha): upgrade slsa generator to v1.9.0

---

pkg/driver/distro/distro.go

/kind cleanup
/area library
Fixes #

chore(pkg/driver): improved error message when err is nil.

---

cmd/driver/cleanup/cleanup_suite_test.go
cmd/driver/cleanup/cleanup_test.go
cmd/driver/install/install_suite_test.go
cmd/driver/install/install_test.go
cmd/driver/printenv/printenv_suite_test.go
cmd/driver/printenv/printenv_test.go

/kind cleanup
/area tests
Implements tests for driver sub commands.
Fixes #

new(cmd/driver): added more driver commands tests.

---

.github/workflows/docker-image.yaml

/kind bug
It appears that the release pipelines are unable to sign the artifact. This upgrades the signature jobs to verify if it is a version issue.
Fixes #

update(ci): upgrade cosign-installer to v3.3.0

---

internal/follower/follower_test.go

/kind cleanup
/area tests
This PR implements tests for Follower `checkRequirements` method.
Fixes #348

chore(internal): added engine version related tests.

---

go.sum

fix: fixed go.sum entry to fix build.

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes a dead link to contributing docs.

fix: Dead link in PR template

---

.github/PULL_REQUEST_TEMPLATE.md
cmd/driver/cleanup/cleanup.go
cmd/driver/install/install.go
cmd/driver/install/install_test.go
pkg/driver/distro/distro.go
pkg/driver/distro/flatcar.go
pkg/driver/distro/generic.go
pkg/driver/distro/generic_test.go
pkg/driver/distro/ubuntu.go

/kind cleanup
Cherry picks:
* https://github.com/falcosecurity/falcoctl/pull/427
* https://github.com/falcosecurity/falcoctl/pull/425
* https://github.com/falcosecurity/falcoctl/pull/407
* https://github.com/falcosecurity/falcoctl/pull/428
From master into the release/v0.7.x branch.
Fixes #

sync: release v0.7.x

---

cmd/registry/push/push.go
pkg/oci/pusher/pusher.go
pkg/oci/pusher/pusher_test.go

/kind bug
> /kind design
/area library
/area cli
/area tests
This PR fixes the push command that does not report the artifact type pushed to the registry.
Fixes #

fix(pusher): correctly report artifact type

---

.github/workflows/docker-image.yaml

> /kind bug
> /kind design
> /area cli
> /area tests
Push falcoctl images to AWS ECR.
Fixes #
#443 

new(CI): add ecr repository

---

.github/workflows/docker-image.yaml
.github/workflows/integration.yaml

> /kind bug
> /kind design
> /area cli
> /area tests
Fix permissions for CI workfow.
Fixes #

fix(ci): add permissions for AWS ecr

---

.github/workflows/docker-image.yaml
.github/workflows/integration.yaml
.github/workflows/release.yaml

> /kind bug
> /kind design
> /area cli
> /area tests
Cherry picking CI updates to `release/v0.7.x` branch.
Fixes #

Kcl/update release v0.7.x

---

.github/workflows/integration.yaml

> /kind bug
> /kind design
> /area cli
> /area tests
new(ci): add provenance for main tag
Fixes #

new(ci): add provenance for main tag

---

.github/workflows/release.yaml

> /kind bug
> /kind design
> /area cli
> /area tests
fix(CI): add permissions to login-to-amazon-ecr job
Fixes #

fix(CI): add permissions to login-to-amazon-ecr job

---

.github/workflows/integration.yaml
.github/workflows/release.yaml

> /kind bug
> /kind design
> /area cli
> /area tests
Thi PR cherry picks CI changes to release/v0.7.x branch
Fixes #

Cherry pick CI changes to release/v0.7.x

---

cmd/registry/pull/pull_test.go
cmd/registry/push/push_test.go
go.mod
go.sum

/kind cleanup
See oras changelog: https://github.com/oras-project/oras-go/releases/tag/v2.4.0.
We already use:
* github.com/opencontainers/image-spec v1.1.0
as requested by the breaking changes in oras 2.4.0.
Fixes #

update(cmd): bumped oras to v.2.4.0.

---

cmd/registry/push/push.go

> /kind bug
/kind cleanup
> /kind design
/area cli
> /area tests
chore(cmd/push): uniform receiver for push command
Fixes #

chore(cmd/push): uniform receiver for push command

---

cmd/driver/cleanup/cleanup.go
cmd/driver/cleanup/cleanup_test.go
cmd/driver/config/config.go
cmd/driver/config/config_test.go
cmd/driver/driver_linux.go
cmd/driver/install/install.go
cmd/driver/install/install_test.go
cmd/driver/printenv/printenv.go
cmd/driver/printenv/printenv_test.go
cmd/root_test.go

/kind cleanup
/area cli
We should be pretty confident that the `driver` related CLI API is now stable.
/cc @falcosecurity/falcoctl-maintainers @alacuku  
/hold
Fixes #

cleanup(cmd/driver): drop preview tag.

---

.goreleaser.yml

fix(goreleaser): disable release build for windows i386.

---

cmd/artifact/install/install.go

/kind bug
/area cli
When using the `install` command to download an artifact and its dependencies, sometimes signature for dependencies was not properly checked even if a signature entry was present in the index. This fixes it.
Fixes #

fix(install): fix missing dependency signature verification

---

cmd/driver/cleanup/cleanup.go
cmd/driver/cleanup/cleanup_test.go
cmd/driver/config/config.go
cmd/driver/config/config_test.go
cmd/driver/driver_linux.go
cmd/driver/install/install.go
cmd/driver/install/install_test.go
cmd/driver/printenv/printenv.go
cmd/driver/printenv/printenv_test.go

/kind cleanup
/area cli
Fixup after https://github.com/falcosecurity/falcoctl/pull/506
Fixes #

chore(cmd): dropped leftover `experimental` for driver-loader.

---

cmd/driver/cleanup/cleanup_test.go
cmd/driver/config/config_test.go
cmd/driver/install/install_test.go
cmd/driver/printenv/printenv_test.go
internal/config/config.go

/kind cleanup
/area library
See https://github.com/falcosecurity/falco/pull/3173
Fixes #

chore(internal): old ebpf probe must have lowest priority.

---

pkg/driver/distro/distro.go
pkg/driver/distro/distro_test.go

/kind bug
/area library
This fix avoids a source of crash.
Fixes #
/milestone v0.8.0

fix(pkg/driver): avoid source of crash during distro Discovery.

---

.github/workflows/integration.yaml
.github/workflows/lint.yaml
.github/workflows/release.yaml
build/Dockerfile

> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #

chore(build): bump go version to 1.22

---

pkg/driver/distro/distro.go

/kind bug
/area library
Fixes #

fix(pkg/driver): create envmap if nil since driverkit expects it.

---

go.mod
go.sum
pkg/driver/distro/distro.go

/kind cleanup
/area library
Fixes #

chore: updated driverkit to v0.19.2

---

cmd/driver/config/config.go
internal/config/config.go

/kind cleanup
/area cli
Fixes #

chore(cmd,internal): expose FALCOCTL_DRIVER_CONFIG_UPDATE_FALCO env var.

---

cmd/driver/driver_linux.go
cmd/driver/install/install.go
cmd/driver/install/install_test.go
pkg/driver/distro/distro.go

/kind cleanup
/area cli
Fixes #

chore(cmd/driver,pkg/driver): allow to disable kernel headers automatic download

---

go.mod

> /kind bug
> /kind design
/area library
> /area cli
> /area tests
chore(go.mod): bump go version to 1.22.5
Fixes #

chore(go.mod): bump go version to 1.22.5

---

build/Dockerfile

> /kind bug
> /kind design
/kind feature
> /area cli
> /area tests
feat(dockerfile): use distroless image for falcoctl docker image
Fixes #

feat(dockerfile): use distroless image for falcoctl docker image

---

README.md
go.mod
pkg/index/fetch/fetch.go
pkg/index/fetch/s3/doc.go
pkg/index/fetch/s3/fetcher.go
pkg/index/fetch/s3/types.go

> /kind bug
> /kind design
/kind feature
/area library
> /area cli
> /area tests
This PR is adding support for S3 as storage backend for indexes
Fixes #606

Feat: Add support for S3 index storage backend

---

Makefile

The target will run independent from the state of the file.
> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #

chore(Makefile): add .PHONY to falcoctl target

---

OWNERS

> /kind bug
> /kind design
> /area cli
> /area tests
I am opening this PR after proposing myself as falcoctl maintainer in today's community call, starting the voting process!
cc @falcosecurity/falcoctl-maintainers 
Fixes #

update(OWNERS): add loresuso to approvers

---

.goreleaser.yml

/kind bug
> /kind design
> /area cli
> /area tests
Fixes #

fix(goreleaser): use latest tag when two tags point to the same commit

---

go.mod
go.sum

/kind cleanup
https://github.com/falcosecurity/driverkit/releases/tag/v0.20.4 includes new falcoctl main with https://github.com/falcosecurity/falcoctl/pull/671 fix.
Fixes #

update(go): bumped driverkit dep to v0.20.4.

---

go.mod

> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #

chore(go.mod): bump go version to 1.23.4

---

.golangci.yml

> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #

fix(CI): remove deprecated configuration from .golangci.yml

---

pkg/driver/type/bpf.go
pkg/driver/type/consts.go
pkg/driver/type/kmod.go
pkg/driver/type/modernbpf.go

> /kind bug
> /kind design
/area library
> /area cli
> /area tests
Fixes #

fix(driver): build specific code only for linux platform

---

go.mod

> /kind bug
> /kind design
> /area cli
> /area tests
Fixes #

chore(toolchain): bump go to version 1.23.7
